### ISSUE TITLE
关于接口请求问题

### ISSUE THREAD

**Issue by abner0914** [VcStrong/JetpackMVVM#1]
1.首先感谢你上传的的项目，让我可以直观学习mvvm；
2.我把项目运行起来，发现只有login和welcome2个页面可以跑；
3.注册页面里面获取验证码功能没有，如果无法注册，也就没有测试账户登录，那首页信息有根据userid来获取的，也无法请求；
4.请问我该如何完整的运行该项目。
再次感谢，你的分享

**Comment by VcStrong** [comment]
IAppRequest中写了注册请求，验证码由于需要第三方短信，所以没有接入，只是页面效果。
注册只需要输入假手机号和密码就可以成功。

**Comment by abner0914** [comment]
你好，按照你的方式注册通过了，但却登录不了，接口返回报错，请问有测试账户么？
以下是日志：
05-13 11:18:55.335 29710-29750/com.vc.wd D/OkHttp: --> POST http://mobile.bwstudent.com/small/user/v1/login
05-13 11:18:55.335 29710-29750/com.vc.wd D/OkHttp: Content-Type: application/x-www-form-urlencoded
05-13 11:18:55.335 29710-29750/com.vc.wd D/OkHttp: Content-Length: 54
05-13 11:18:55.336 29710-29750/com.vc.wd D/OkHttp: phone=XXXXXXXXXX&pwd=F920AB3EA2E14FDCB1FE234C1D577812
05-13 11:18:55.336 29710-29750/com.vc.wd D/OkHttp: --> END POST (54-byte body)
05-13 11:18:55.422 29710-29750/com.vc.wd D/OkHttp: <-- 200 http://mobile.bwstudent.com/small/user/v1/login (86ms)
05-13 11:18:55.423 29710-29750/com.vc.wd D/OkHttp: Server: nginx/1.14.0
05-13 11:18:55.423 29710-29750/com.vc.wd D/OkHttp: Date: Wed, 13 May 2020 03:18:50 GMT
05-13 11:18:55.423 29710-29750/com.vc.wd D/OkHttp: Content-Type: application/json;charset=UTF-8
05-13 11:18:55.423 29710-29750/com.vc.wd D/OkHttp: Content-Length: 67
05-13 11:18:55.423 29710-29750/com.vc.wd D/OkHttp: Connection: keep-alive
05-13 11:18:55.423 29710-29750/com.vc.wd D/OkHttp: {"message":"登陆失败,手机号或密码错误","status":"1001"}
05-13 11:18:55.423 29710-29750/com.vc.wd D/OkHttp: <-- END HTTP (67-byte body)

**Comment by VcStrong** [comment]
抱歉，老铁，写完没注意，注册业务忘记调试了。
刚刚更新了代码，重新clone或者pull，注册-登录即可，取消了原来的MD5密码加密，现在后端接口验证规则变了，所以前端只能提交明文密码。
本次更新日志：
修复登录页无法进入注册页bug
修复点击注册崩溃bug
核对后台接口：注册的密码规则是数字加字母超过8位即可
测试账号：13126965106   密码：111111aa

**Comment by WY1479052860** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"VcStrong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 中午12:30
收件人:&nbsp;"VcStrong/JetpackMVVM"<JetpackMVVM@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [VcStrong/JetpackMVVM] 关于接口请求问题 (#1)





 
Reopened #1.

**Comment by cclovera** [comment]
你好~~java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference  当请求服务返回数据中含有字段值为null时报这个错
