### ISSUE TITLE
不同的module之间如何打开同一个activity

### ISSUE THREAD

**Issue by greatflag** [VcStrong/JetpackMVVM#11]
比如消息模块 我的模块 主页模块 都要打开用户资料页面activity，这个activity怎么共享呢？

**Comment by VcStrong** [comment]
Arouter，WDActivity和WDViewModel中都封装了intent跳转页面的方法，可以传递bundle。

**Comment by greatflag** [comment]
> Arouter，WDActivity和WDViewModel中都封装了intent跳转页面的方法，可以传递bundle。

您好, 我把activity放common里, arouter找不到, 哪里需要配置一下?

**Comment by VcStrong** [comment]
> > Arouter，WDActivity和WDViewModel中都封装了intent跳转页面的方法，可以传递bundle。
> 
> 您好, 我把activity放common里, arouter找不到, 哪里需要配置一下?

仿照module.gradle中写：
`        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }`

`annotationProcessor 'com.alibaba:arouter-compiler:1.2.1'`

**Comment by greatflag** [comment]
是我加了kotlin的问题, 用kapt配置aroute后可以打开了.

**Comment by greatflag** [comment]
![image](https://user-images.githubusercontent.com/6038392/99252061-5e9cf380-2849-11eb-9a3d-30d8954c125a.png)
