### ISSUE TITLE
WDFragViwModel如果管理生命周期

### ISSUE THREAD

**Issue by zfy1988** [VcStrong/JetpackMVVM#12]
WDFragViwModel未继承VeiwModel也没有实现LifecycleObserver, 那么它如果管理生命周期？

**Comment by VcStrong** [comment]
Fragment使用的是Activity的viewmodel，WDFragViewModel是一个伪类，相当于WDViewModel的子节点，可以通过WDViewModel将生命周期进行下发；目前create()方法就是使用的这种方式；
我这种设计实际上把viewmodel和LifecycleObserver合并了，由于LifecycleObserver可以观察声明周期，也可以被多个类实现；
那么可以更改一下代码设计：WDFragViewModel实现LifecycleObserver，通过WDViewModel提供get方法得到各个WDFragViewModel，然后使用getLifecycle().addObserver()添加，这样伪类中也可以使用注解生命周期了。

**Comment by VcStrong** [comment]
@zfy1988 已更新框架，WDFragViewModel支持生命周期管理。

**Comment by zfy1988** [comment]
> @zfy1988 已更新框架，WDFragViewModel支持生命周期管理。
