### ISSUE TITLE
BoostMultiDex与ARouter的兼容性请教

### ISSUE THREAD

**Issue by rouxianmantou** [VcStrong/JetpackMVVM#14]
你好，我搜到您的项目好像在同时用BoostMultiDex和ARouter，想咨询一下他们不会冲突么？没环境测试，请教一下，谢谢！

**Comment by VcStrong** [comment]
没有冲突，可以 看一下common包下build.gradle，里面有依赖版本

**Comment by rouxianmantou** [comment]
谢谢，昨天报了个bug，正好前几个月给4.x加了boostmultidex，然后又报了个4.x跳转的bug，怀疑是arouter没兼容
昨晚看了看是别的问题，他俩确实不冲突
