### ISSUE TITLE
项目无法运行问题

### ISSUE THREAD

**Issue by Movement123** [VcStrong/JetpackMVVM#2]
我用git clone下来项目后，运行报错，信息如下：
ERROR: This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
The following AndroidX dependencies are detected: androidx.appcompat:appcompat:1.1.0, androidx.core:core:1.1.0, androidx.slidingpanelayout:slidingpanelayout:1.0.0, androidx.versionedparcelable:versionedparcelable:1.1.0, androidx.fragment:fragment:1.1.0, androidx.customview:customview:1.0.0, androidx.swiperefreshlayout:swiperefreshlayout:1.0.0, androidx.constraintlayout:constraintlayout-solver:1.1.3, androidx.interpolator:interpolator:1.0.0, androidx.loader:loader:1.0.0, androidx.activity:activity:1.0.0, androidx.drawerlayout:drawerlayout:1.0.0, androidx.collection:collection:1.1.0, androidx.viewpager:viewpager:1.0.0, androidx.localbroadcastmanager:localbroadcastmanager:1.0.0, androidx.arch.core:core-common:2.1.0, androidx.savedstate:savedstate:1.0.0, androidx.annotation:annotation:1.1.0, androidx.lifecycle:lifecycle-common:2.2.0, androidx.appcompat:appcompat-resources:1.1.0, androidx.lifecycle:lifecycle-viewmodel:2.2.0, androidx.legacy:legacy-support-core-ui:1.0.0, androidx.constraintlayout:constraintlayout:1.1.3, androidx.lifecycle:lifecycle-livedata:2.2.0, androidx.arch.core:core-runtime:2.1.0, androidx.lifecycle:lifecycle-livedata-core:2.2.0, androidx.legacy:legacy-support-core-utils:1.0.0, androidx.documentfile:documentfile:1.0.0, androidx.cursoradapter:cursoradapter:1.0.0, androidx.vectordrawable:vectordrawable-animated:1.1.0, androidx.recyclerview:recyclerview:1.0.0, androidx.vectordrawable:vectordrawable:1.1.0, androidx.coordinatorlayout:coordinatorlayout:1.0.0, androidx.asynclayoutinflater:asynclayoutinflater:1.0.0, androidx.lifecycle:lifecycle-runtime:2.2.0, androidx.print:print:1.0.0
Affected Modules: app, common, open_im, open_login, open_main, open_push

-----------------------------------------------------------------------------------------------------------
我的gradle-wrapper.properties配置信息如下：
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
android.useAndroidX=true
android.enableJetifier=true
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

**Comment by VcStrong** [comment]
可能原因是你的Android Studio没有开启AndroidX支持，gradle-wrapper.properties不需要这么写。
可以试一下：Android Studio中的选项栏-Refactor--->Migrate to AndroidX，一通确定之后，确定移植AndroidX。

**Comment by VcStrong** [comment]
我的gradle-wrapper.properties:
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip

**Comment by Movement123** [comment]
谢谢您的回复。这个问题我之前也想到过，也试着Refactor--->Migrate to AndroidX，但是最后还是报同样的错。我还换了一个新的电脑，git clone下工程打开，也是同样的问题。我确定这两台电脑上都可以运行AndroidX项目。

**Comment by VcStrong** [comment]
抱歉，gradle.properties文件中包含androidX配置，之前没有提交，你更新一下就可以了。
