### ISSUE TITLE
关于请求不同域名的问题

### ISSUE THREAD

**Issue by dewi23** [VcStrong/JetpackMVVM#3]
/**
     * 此方法用来确定采用的Rtrofit中baseUrl
     * 由于Retrofit特性，baseUrl不能随意改动，当大项目拥有
     * 多个域名控制不同业务的时候，则需要不同的Retrofit
     * @TODO 可以根据需要在子类中重写
     */
    protected int getRequestType() {
        return REQUEST_TYPE_DEFAULT;
    }

    /**
     * 返回值类型，方便不同接口返回数据结构不同的情况，参见{@link #getConsumer(DataCall)}
     * 应对大项目多数据结构
     * @TODO 可以根据需要在子类中重写
     */
    protected int getResponseType() {
        return RESPONSE_TYPE_DEFAULT;
    }

这个怎么用。我现在项目中调用了不同的域名

**Comment by VcStrong** [comment]
1. 根据域名新建不同的API接口类；
2. NetworkManager类中，①增加新域名retrofit对象，baseUrl可以写死，也可以写在config.gradle中，使用BuildConfig访问；②修改create方法中if判断，使用新域名retrofit加载api接口；
3. 在自己业务的VIewModel中重写getRequestType方法，返回接口类型。
4. 在WDViewModel中增加接口类型，方便NetworkManager中的判断使用和WDViewModel子类使用，命名参照：REQUEST_TYPE_*；如果返回值数据结构也不一样，请参照RESPONSE_TYPE_*的使用。

**Comment by AsWinds** [comment]
> 1. 根据域名新建不同的API接口类；
> 2. NetworkManager类中，①增加新域名retrofit对象，baseUrl可以写死，也可以写在config.gradle中，使用BuildConfig访问；②修改create方法中if判断，使用新域名retrofit加载api接口；
> 3. 在自己业务的VIewModel中重写getRequestType方法，返回接口类型。
> 4. 在WDViewModel中增加接口类型，方便NetworkManager中的判断使用和WDViewModel子类使用，命名参照：REQUEST_TYPE_*；如果返回值数据结构也不一样，请参照RESPONSE_TYPE_*的使用。

您好，感谢您的分享。如果要再一个ViewModel内请求多个不同域名，是否能实现。

**Comment by VcStrong** [comment]
iRequest作为ViewModel中的主请求接口无法变动；如果包含其他baseurl的请求接口，可以通过调用NetworkManager.instance().create()进行获取，另外这个create方法可能需要你根据类型自行修改；
在viewmodel得到其他接口对象后，调用方式依旧使用request(Observable observable, final DataCall dataCall)完成
