### ISSUE TITLE
ConstantPlugin无法找到

### ISSUE THREAD

**Issue by qiufengyun** [VcStrong/JetpackMVVM#4]
Could not GET 'https://jitpack.io/com/github/VcStrong/ConstantPlugin/0.0.1/ConstantPlugin-0.0.1.pom'. Received status code 403 from server: Forbidden

**Comment by Jsonjia** [comment]
我也遇到这问题，希望作者能解答下

**Comment by VcStrong** [comment]
@Jsonjia @qiufengyun 抱歉了，jitpack.io关闭了ConstantPlugin这个插件的访问，需要付费才可以恢复访问。

改为本地引入这个插件（参见项目中的repo文件夹），更新项目就可以使用了。

**Comment by Jsonjia** [comment]
现在可以正常运行了，但是登录失败

**Comment by VcStrong** [comment]
@Jsonjia 你好，修复了，更新再试。后端改了接口接收数据为json类型。
