### ISSUE TITLE
关于打包问题。

### ISSUE THREAD

**Issue by dewi23** [VcStrong/JetpackMVVM#5]
为何我打包就打了一个空白的。其他model好像都没有

**Comment by VcStrong** [comment]
config.gradle中的allPackage改为true全部参与打包。
`//全部都打包，如果只运行模块，请改为false；true则所有模块都参与打包
    allPackage = true`

**Comment by dewi23** [comment]
找到方法了。另外同事在他的模块下面写了<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:networkSecurityConfig="@xml/network_security_config"
        android:requestLegacyExternalStorage="true"
        android:name="com.sz.tokenpro.library_base.core.BaseApplication"
        android:theme="@style/AppTheme" >代码。蛋疼。
