### ISSUE TITLE
关于打包

### ISSUE THREAD

**Issue by dewi23** [VcStrong/JetpackMVVM#6]
为什么打包后几个模块业务都没有啊。路由报 ARouter::There is no route match the path [/xxx/xxx], in group [xxx][ ]”

**Comment by VcStrong** [comment]
@dewi23 查看build日志，如果所有模块都参与了打包，发一下config.gradle配置

**Comment by dewi23** [comment]
> @ dewi23查看build日志，如果所有模块都参与了打包，发一下config.gradle配置

ext {

    //开发-分支
    dev = [
            branch : "dev",
            applicationId    : "com.sz.tokenpro.dev",
            versionCode      : 202007201,
            versionName      : "2.1dev",
            appName : "TokenPro开发",
            serverUrl : "http://192.168.101.30:8881/",
            baiduUrl : "http://192.168.101.30:8883/"
//            im_key : "1111kkkkkk",
//            push_key : "1111ppppp"
    ]

    //测试-分支
    beta = [
            branch : "beta",
            applicationId    : "com.sz.tokenpro.beta",
            versionCode      : 202007201,
            versionName      : "2.1beta",
            appName : "TokenProbeta",
            serverUrl : "http://192.168.101.30:8881/",
            baiduUrl : "http://192.168.101.30:8883/"
//            im_key : "2222kkkkkk",
//            push_key : "2222ppppp"
    ]

    //发布版上线-分支
    release = [
            branch : "release",
            applicationId    : "com.sz.tokenpro",
            versionCode      : 1,
            versionName      : "1.0",
            appName : "TokenProrelease",
            serverUrl : "http://192.168.101.30:8881/",
            baiduUrl : "http://192.168.101.30:8883/"
//            im_key : "3333kkkkkk",
//            push_key : "3333ppppp"
    ]

    //①方便自定义各种常量，统一项目中配置输出
    //②方便后续接入即时通讯、推送等服务之后，不同分支使用不同的第三方api_key，防止开发或者测试阶段发送"test"这样的推送消息造成A类事故
    //根据项目阶段自行改变（dev,beta,release），方便各部门协作，减少沟通成本
    //千万不要错误的认成build.gradle中debug和release，上面只是项目各阶段的配置，和apk打包互不影响。
    active = release

    //建议用来记录不会因为发布分支改变的参数
    SDK_VERSION = [
            compileSdkVersion: 29,
            minSdkVersion    : 21,//4.0.3
            targetSdkVersion : 29
    ]

    //全部都打包，如果只运行模块，请改为false；true则所有模块都参与打包
    allPackage = true
    //需要运行的组件，当allPackage为false的时候，此变量生效，模块名参照settings.gradle中的
    needPackage = ["module_main"]
   //这里是不是要把其他module加进来？
}

**Comment by VcStrong** [comment]
@dewi23 allPackage = true这个就代表全量打包，你可以使用android studio的Analyze apk分析一下app/build/outputs/debug下的apk，查看一下包内的AndroidManifest.xml和classdex下的源码是否缺少。

**Comment by dewi23** [comment]
> @ dewi23 allPackage = true这个就代表全量打包，你可以使用android studio的分析apk分析一下app / build / outputs / debug下的apk，查看一下包内的AndroidManifest.xml和classdex下的缓存是否存在。

debug编译没有问题。签名打包后就出现问题了。蛋疼

**Comment by dewi23** [comment]
> > @ dewi23 allPackage = true这个就代表全量打包，你可以使用android studio的分析apk分析一下app / build / output / debug下的apk，查看一下包内的AndroidManifest.xml和classdex下的缓存是否存在。
> 
> debug编译没有问题。签名打包后就出现问题了。蛋疼

混淆导致的。蛋疼，，

**Comment by VcStrong** [comment]
@dewi23 好的，对于这个架构有使用建议可以及时反馈，谢谢老铁
