### ISSUE TITLE
发现重大扩展问题

### ISSUE THREAD

**Issue by Zpsgithub** [VcStrong/JetpackMVVM#7]
使用多个fragment+viewpager时，数据就不显示了

**Comment by VcStrong** [comment]
@Zpsgithub 可能是你使用viewpager和Fragment或者Fragment嵌套Fragment的问题，UI和本框架没有多大关系的；今天有时间我试了一下没有问题，更新一下代码，更新日志放在README.md中，参见”三、分支更新日志（倒叙）“

**Comment by Zpsgithub** [comment]
感谢大佬
