### ISSUE TITLE
大佬 请教些问题谢谢

### ISSUE THREAD

**Issue by Zpsgithub** [VcStrong/JetpackMVVM#8]
1.子fragment viewmodel如何关联主fragment ，因为首页有顶部滑动标签（类似今日头条tab）， 我想用tablayout+viewpager+fragment+recyclerview  
2.阿里路由有时候点击跳转事件不响应

**Comment by VcStrong** [comment]
@Zpsgithub  Activity中有getFragmentManager，Fragment中有getChildFragmentManager，这种设计思路可以借鉴过来，Activity中通过WDViewModel对Fragment的WDFragViewModel进行管理，Fragment的WDFragViewModel可以继续管理其他Fragment的WDFragment，然后把Activity中参数进行下发，另外可以定义专属于Fragment的LiveData参数，数据通信基本可以保证。

阿里路由跳转不响应的话，建议你多了解一下Arouter关于组件化使用，组件之间一级路径名必须不一样，也有可能组件化没有打包进去等各种问题。

**Comment by Zpsgithub** [comment]
您好 大佬，请教您一下 是WDFragViewModel复写：主Fragment的viewModel关联其他 Fragment的viewmodel的方法吗？

**Comment by VcStrong** [comment]
@Zpsgithub 对，依旧是其他fragment的vm继承WDFragViewModel，然后在WDFragViewModel中仿照WDViewModel写一个Fragvm的list，然后分发几个关键参数就可以，那几个关键参数有一个管理数据的使用的Message的livedata，这个就是分发各种数据，类似于handler，但代码优雅程度高于handler
