### ISSUE TITLE
插件编译太慢了

### ISSUE THREAD

**Issue by Zpsgithub** [VcStrong/JetpackMVVM#9]

**Comment by VcStrong** [comment]
插件包含两个
classpath "io.objectbox:objectbox-gradle-plugin:2.5.1"
classpath 'com.github.VcStrong:ConstantPlugin:0.0.1'

objectbox每次build都会扫描注解生成相关数据库类，这个可以看看github上objectbox官方工程有没有相关编译建议。

ConstantPlugin常量插件可以关闭enable false即可。这个插件程序特别少，运行速度可以忽略不计。如果完全不需要的化，可以按照”三、分支更新日志（倒叙）中 4. mvvm-v3.1 2020.06.12“常量插件的说明，把插件删除，大可放心，删除不影响程序已生成的常量类。

`在module的build.gradle中使用：
apply plugin: 'com.vc.constant'//启用常量插件
constant {
    enable false//不进行编译，不写的话，默认每次都进行编译，查看build日志
    moduleName "common"//生成新代码存放的moduleName
    packageName "com.vc.wd.common.util"//生成的新代码放在哪个包下
    className "Constant"//生成的常量类名
    fieldMap = [
        ACTIVITY_URL_MAIN : '/main/MainActivity',
        ACTIVITY_URL_ADD_CIRCLE : '/main/AddCircleActivity'
    ]//属性参数
}`

gredle编译速度慢可以查看build output最后一行 build analyzer对一次build过程进行分析，一般都是查找依赖耗费大量时间，你可以去掉：
`maven{ url 'https://maven.aliyun.com/repository/jcenter'}
        maven{ url 'https://maven.aliyun.com/repository/google'}
        `
把常量插件依赖的repo库放到最上方。

**Comment by Zpsgithub** [comment]
按您说的去做解决了，再次感谢大佬。不过还要请教一个问题 我在打包的时候 报错：

app/build/intermediates/project_dex_archive/release/out/yueliankj/com/utils/Constant.dex
Type yueliankj.com.utils.Constant is defined multiple times: /Users/user/showlive_android/app/build/intermediates/project_dex_archive/release/out/yueliankj/com/utils/Constant.dex, /Users/user/showlive_android/app/build/intermediates/sub_project_dex_archive/release/out/42c33276fa27f9f8b3f9e03a4b007146bb05a07cd50baceac03049222203f054_1.jar:classes.dex

**Comment by VcStrong** [comment]
https://blog.csdn.net/VcStrong/article/details/99670983
组件合并打包的一些经验；
从你发的看来，应该是类重复或者组件的AndroidManifest.xml中package重复；例如A组件有一个类是com.test.util.FileUtil.java，B组件中有一个类也是com.test.util.FileUtil.java，那么合并打包必然报错；另外清单文件中package决定了R类是否冲突；所以尽量保持组件的java包名和进程包名为：工程包名+组件名
